version: "3.7"

services:
  mysql:
    container_name: adm_videos_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_videos_network
    # volumes:
    #   - ./mysql:/var/lib/mysql

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3.8.3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - adm_videos_network

networks:
  adm_videos_network:
    driver: bridge
