###
GET http://localhost:3000
###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/b6862b8e-9bb8-48aa-ae52-58e313c96bb2
###
Post http://localhost:3000/categories
Content-Type: application/json

{
  "name":"Movie"
}

###
PUT http://localhost:3000/categories/b6862b8e-9bb8-48aa-ae52-58e313c96bb2
Content-Type: application/json

{
  "name":"Movie-2"
}

###
DELETE  http://localhost:3000/categories/b6862b8e-9bb8-48aa-ae52-58e313c96bb2
Content-Type: application/json

