version: '3.8'

services:
  app:
    # user: "${UID}:${GID}"
    build:
      context: .
    container_name: micro-videos-typescript-app
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000