amqp:
  host: localhost
  port: 5672
  username: rabbitmq
  password: 123456

logging:
  level: ROOT
mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ampq.RabbitAutoConfiguration